"""initial_schema

Revision ID: b7c0bdd8b4f5
Revises:
Create Date: 2026-03-01 15:36:22.773572

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7c0bdd8b4f5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "theses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "linked_tickers",
            postgresql.ARRAY(sa.String(length=10)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger_description", sa.Text(), nullable=True),
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_thesis_status", "theses", ["status"], unique=False)
    op.create_table(
        "companies",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector_id", sa.Integer(), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("market_cap_range", sa.String(length=20), nullable=True),
        sa.Column("is_watchlist", sa.Boolean(), nullable=False),
        sa.Column("last_processed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index("idx_company_sector", "companies", ["sector_id"], unique=False)
    op.create_index(
        "idx_company_watchlist", "companies", ["is_watchlist"], unique=False
    )
    op.create_table(
        "derived_metrics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("calculated_value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("period_identifier", sa.String(length=20), nullable=True),
        sa.Column("calculation_method", sa.Text(), nullable=False),
        sa.Column("source_fact_ids", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_derived_company_metric",
        "derived_metrics",
        ["company_ticker", "metric_name"],
        unique=False,
    )
    op.create_index(
        "idx_derived_period",
        "derived_metrics",
        ["company_ticker", "metric_name", "period_identifier"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("document_type", sa.String(length=30), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("publish_date", sa.Date(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_uri", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("processing_tier", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index("idx_doc_company", "documents", ["company_ticker"], unique=False)
    op.create_index("idx_doc_publish_date", "documents", ["publish_date"], unique=False)
    op.create_index("idx_doc_status", "documents", ["status"], unique=False)
    op.create_index(
        "idx_doc_type_company",
        "documents",
        ["document_type", "company_ticker"],
        unique=False,
    )
    op.create_table(
        "company_relationships",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_a_ticker", sa.String(length=10), nullable=False),
        sa.Column("company_b_ticker", sa.String(length=10), nullable=False),
        sa.Column("relationship_type", sa.String(length=20), nullable=False),
        sa.Column("source_document_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_seen",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=True,
        ),
        sa.Column(
            "last_seen",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "company_a_ticker != company_b_ticker", name="ck_no_self_relationship"
        ),
        sa.ForeignKeyConstraint(
            ["company_a_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["company_b_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_a_ticker",
            "company_b_ticker",
            "relationship_type",
            name="uq_company_relationship",
        ),
    )
    op.create_index(
        "idx_comprel_a", "company_relationships", ["company_a_ticker"], unique=False
    )
    op.create_index(
        "idx_comprel_b", "company_relationships", ["company_b_ticker"], unique=False
    )
    op.create_table(
        "document_sections",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("section_identifier", sa.String(length=50), nullable=False),
        sa.Column("section_order", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "section_identifier", name="uq_doc_section"),
    )
    op.create_index(
        "idx_section_doc", "document_sections", ["document_id"], unique=False
    )
    op.create_index("idx_section_status", "document_sections", ["status"], unique=False)
    op.create_table(
        "mentions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("source_company_ticker", sa.String(length=10), nullable=False),
        sa.Column("mentioned_ticker", sa.String(length=10), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("mention_type", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_company_ticker"],
            ["companies.ticker"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_mention_document", "mentions", ["document_id"], unique=False)
    op.create_index(
        "idx_mention_mentioned", "mentions", ["mentioned_ticker"], unique=False
    )
    op.create_index(
        "idx_mention_source", "mentions", ["source_company_ticker"], unique=False
    )
    op.create_table(
        "risk_factors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("risk_category", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_new_this_period", sa.Boolean(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_risk_category", "risk_factors", ["risk_category"], unique=False
    )
    op.create_index(
        "idx_risk_company", "risk_factors", ["company_ticker"], unique=False
    )
    op.create_index(
        "idx_risk_new", "risk_factors", ["is_new_this_period"], unique=False
    )
    op.create_table(
        "sentiment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("assessed_date", sa.Date(), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=False),
        sa.Column("narrative_category", sa.String(length=30), nullable=True),
        sa.Column("document_id", sa.BigInteger(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sentiment_score >= -1 AND sentiment_score <= 1",
            name="ck_sentiment_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sentiment_company_date",
        "sentiment",
        ["company_ticker", "assessed_date"],
        unique=False,
    )
    op.create_index(
        "idx_sentiment_narrative", "sentiment", ["narrative_category"], unique=False
    )
    op.create_index("idx_sentiment_source", "sentiment", ["source_type"], unique=False)
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=True),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.Column("prompt_template_id", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["document_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_proclog_document", "processing_logs", ["document_id"], unique=False
    )
    op.create_index(
        "idx_proclog_model", "processing_logs", ["model_name"], unique=False
    )
    op.create_index("idx_proclog_success", "processing_logs", ["success"], unique=False)
    op.create_index(
        "idx_proclog_timestamp", "processing_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "raw_facts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("period_type", sa.String(length=20), nullable=True),
        sa.Column("period_identifier", sa.String(length=20), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name="ck_fact_confidence_range",
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["document_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_fact_company", "raw_facts", ["company_ticker"], unique=False)
    op.create_index("idx_fact_document", "raw_facts", ["document_id"], unique=False)
    op.create_index("idx_fact_metric", "raw_facts", ["metric_name"], unique=False)
    op.create_index(
        "idx_fact_period",
        "raw_facts",
        ["company_ticker", "metric_name", "period_identifier"],
        unique=False,
    )
    op.create_table(
        "summaries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_ticker", sa.String(length=10), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("summary_type", sa.String(length=30), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_ticker"],
            ["companies.ticker"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["document_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_summary_company", "summaries", ["company_ticker"], unique=False
    )
    op.create_index("idx_summary_document", "summaries", ["document_id"], unique=False)
    op.create_index("idx_summary_type", "summaries", ["summary_type"], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        CREATE INDEX idx_doc_queue
        ON documents (status, ingested_at)
        WHERE status IN ('queued', 'processing')
    """)

    op.execute("""
        CREATE INDEX idx_section_queue
        ON document_sections (status)
        WHERE status IN ('queued', 'processing')
    """)

    op.execute("""
        CREATE INDEX idx_summary_embedding_hnsw
        ON summaries USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    op.execute("""
        CREATE INDEX idx_thesis_tickers
        ON theses USING gin (linked_tickers)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS idx_thesis_tickers")
    op.execute("DROP INDEX IF EXISTS idx_summary_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS idx_section_queue")
    op.execute("DROP INDEX IF EXISTS idx_doc_queue")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_summary_type", table_name="summaries")
    op.drop_index("idx_summary_document", table_name="summaries")
    op.drop_index("idx_summary_company", table_name="summaries")
    op.drop_table("summaries")
    op.drop_index("idx_fact_period", table_name="raw_facts")
    op.drop_index("idx_fact_metric", table_name="raw_facts")
    op.drop_index("idx_fact_document", table_name="raw_facts")
    op.drop_index("idx_fact_company", table_name="raw_facts")
    op.drop_table("raw_facts")
    op.drop_index("idx_proclog_timestamp", table_name="processing_logs")
    op.drop_index("idx_proclog_success", table_name="processing_logs")
    op.drop_index("idx_proclog_model", table_name="processing_logs")
    op.drop_index("idx_proclog_document", table_name="processing_logs")
    op.drop_table("processing_logs")
    op.drop_index("idx_sentiment_source", table_name="sentiment")
    op.drop_index("idx_sentiment_narrative", table_name="sentiment")
    op.drop_index("idx_sentiment_company_date", table_name="sentiment")
    op.drop_table("sentiment")
    op.drop_index("idx_risk_new", table_name="risk_factors")
    op.drop_index("idx_risk_company", table_name="risk_factors")
    op.drop_index("idx_risk_category", table_name="risk_factors")
    op.drop_table("risk_factors")
    op.drop_index("idx_mention_source", table_name="mentions")
    op.drop_index("idx_mention_mentioned", table_name="mentions")
    op.drop_index("idx_mention_document", table_name="mentions")
    op.drop_table("mentions")
    op.drop_index("idx_section_status", table_name="document_sections")
    op.drop_index("idx_section_doc", table_name="document_sections")
    op.drop_table("document_sections")
    op.drop_index("idx_comprel_b", table_name="company_relationships")
    op.drop_index("idx_comprel_a", table_name="company_relationships")
    op.drop_table("company_relationships")
    op.drop_index("idx_doc_type_company", table_name="documents")
    op.drop_index("idx_doc_status", table_name="documents")
    op.drop_index("idx_doc_publish_date", table_name="documents")
    op.drop_index("idx_doc_company", table_name="documents")
    op.drop_table("documents")
    op.drop_index("idx_derived_period", table_name="derived_metrics")
    op.drop_index("idx_derived_company_metric", table_name="derived_metrics")
    op.drop_table("derived_metrics")
    op.drop_index("idx_company_watchlist", table_name="companies")
    op.drop_index("idx_company_sector", table_name="companies")
    op.drop_table("companies")
    op.drop_index("idx_thesis_status", table_name="theses")
    op.drop_table("theses")
    op.drop_table("sectors")
    # ### end Alembic commands ###
